# Global SDG Data Series Catalogue
This notebook illustrates a series of steps necessary to create a catalog of the data series included in the Global SDG Indicator Framework

## Initial settings

In [173]:
import pandas as pd
import os 

dir_path = os.path.dirname(os.path.realpath('__file__'))
print(dir_path)

global_indicator_dir = r'../Global Indicator Framework/'


print('global indicator framework dir: ' + global_indicator_dir)


output_dir = r'../SDG-Matrix/Output/'
print('sdg matix outputs dir: ' + output_dir)

C:\Users\L.GonzalezMorales\Documents\GitHub\PCBS\notebooks
global indicator framework dir: ../Global Indicator Framework/
sdg matix outputs dir: ../SDG-Matrix/Output/

## Global indicator framework

In [161]:
indicator_list = pd.read_excel(global_indicator_dir + 'IndicatorList_20190323.xlsx')
indicator_list.head(10)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode
0,1,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101
1,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201
2,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.2,"Proportion of men, women and children of all a...",C010202
3,1,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301
4,1,End poverty in all its forms everywhere,NaN,1.4,"By 2030, ensure that all men and women, in par...",1.4.1,Proportion of population living in households ...,C010401
5,1,End poverty in all its forms everywhere,NaN,1.4,"By 2030, ensure that all men and women, in par...",1.4.2,Proportion of total adult population with secu...,C010402
6,1,End poverty in all its forms everywhere,NaN,1.5,"By 2030, build the resilience of the poor and ...",1.5.1,"Number of deaths, missing persons and directly...",C200303
7,1,End poverty in all its forms everywhere,NaN,1.5,"By 2030, build the resilience of the poor and ...",1.5.2,Direct economic loss attributed to disasters i...,C010502
8,1,End poverty in all its forms everywhere,NaN,1.5,"By 2030, build the resilience of the poor and ...",1.5.3,Number of countries that adopt and implement n...,C200304
9,1,End poverty in all its forms everywhere,NaN,1.5,"By 2030, build the resilience of the poor and ...",1.5.4,Proportion of local governments that adopt and...,C200305

## Tier classification

In [162]:
tier_classification = pd.read_excel(global_indicator_dir + 'TierCllassification_20190213.xlsx')
tier_classification.head(10)

,IndicatorCode,Tier,Tier_Detailed,Notes
0,C010101,I,Tier I,NaN
1,C010201,I,Tier I,NaN
2,C010202,II,Tier II,NaN
3,C010301,II,Tier II,IAEG-SDG 3rd meeting: Lack of sufficient data ...
4,C010401,II,Tier II,Reviewed at Sept 2018 WebEx meeting. (classifi...
5,C010402,II,Tier II,Reviewed at 6th IAEG-SDG meeting (classified a...
6,C010502,II,Tier II,Sendai modification; Reviewed at 5th IAEG-SDG ...
7,C010a01,III,Tier III,UNSC 48 Refinement; Reviewed at 5th IAEG-SDG m...
8,C010a02,II,Tier II,IAEG-SDG 3rd meeting: There is an established ...
9,C010a03,III,Tier III,UNSC 48 Refinement; Reviewed at 5th IAEG-SDG m...

## Global data series

In [164]:
series = pd.read_json('https://unstats.un.org/SDGAPI/v1/sdg/Series/List?allreleases=false')
series.head(10)

,code,description,goal,indicator,release,target,uri
0,ER_MTN_GRNCVI,Mountain Green Cover Index,[15],[15.4.2],2019.Q1.G.01,[15.4],/v1/sdg/Series/ER_MTN_GRNCVI
1,ER_UNK_LBREDN,Local breeds classified as being at unknown le...,[2],[2.5.2],2019.Q1.G.01,[2.5],/v1/sdg/Series/ER_UNK_LBREDN
2,ER_WAT_PROCED,Proportion of countries with clearly defined p...,[6],[6.b.1],2019.Q1.G.01,[6.b],/v1/sdg/Series/ER_WAT_PROCED
3,FB_ATM_TOTL,Number of automated teller machines (ATMs) per...,[8],[8.10.1],2019.Q1.G.01,[8.10],/v1/sdg/Series/FB_ATM_TOTL
4,FB_BNK_ACCSS,Proportion of adults (15 years and older) with...,[8],[8.10.2],2019.Q1.G.01,[8.10],/v1/sdg/Series/FB_BNK_ACCSS
5,ER_H2O_STRESS,Level of water stress: freshwater withdrawal a...,[6],[6.4.2],2019.Q1.G.01,[6.4],/v1/sdg/Series/ER_H2O_STRESS
6,ER_H2O_FWTL,Proportion of fish stocks within biologically ...,[14],[14.4.1],2019.Q1.G.01,[14.4],/v1/sdg/Series/ER_H2O_FWTL
7,ER_H2O_FISHOVEXP,Proportion of fish stocks that are overexploit...,[14],[14.4.1],2019.Q1.G.01,[14.4],/v1/sdg/Series/ER_H2O_FISHOVEXP
8,ER_GRF_ANIMSTOR,Proportion of local breeds with genetic materi...,[2],[2.5.1],2019.Q1.G.01,[2.5],/v1/sdg/Series/ER_GRF_ANIMSTOR
9,ER_GRF_ANIMRCNTN,Number of local breeds for which sufficient ge...,[2],[2.5.1],2019.Q1.G.01,[2.5],/v1/sdg/Series/ER_GRF_ANIMRCNTN

In [165]:
global_series = []

for index, row in series.iterrows():
    
    series_id = row['code']
    series_desc = row['description']
    
    for i in range(len(row['indicator'])):
    
        series_dict = {}
        
        goal_id =  row['goal'][i]
        target_id = row['target'][i]
        indicator_id = row['indicator'][i]
        release = row['release']
        
        series_dict['Goal'] = goal_id
        series_dict['Target'] = target_id
        series_dict['Indicator'] = indicator_id
        series_dict['Series'] = series_id
        series_dict['SeriesDesc'] = series_desc
        
        series_attr = pd.read_json('https://unstats.un.org/SDGAPI/v1/sdg/Series/'+series_id+'/Attributes')
        series_dict['Units'] = series_attr.loc[series_attr['id'] == 'Units'].iloc[0]['codes'][0]['sdmx']

        
        global_series.append(series_dict)

global_series = pd.DataFrame(global_series)
global_series.head(6)

,Goal,Indicator,Series,SeriesDesc,Target,Units
0,15,15.4.2,ER_MTN_GRNCVI,Mountain Green Cover Index,15.4,INDEX
1,2,2.5.2,ER_UNK_LBREDN,Local breeds classified as being at unknown le...,2.5,NUMBER
2,6,6.b.1,ER_WAT_PROCED,Proportion of countries with clearly defined p...,6.b,PERCENT
3,8,8.10.1,FB_ATM_TOTL,Number of automated teller machines (ATMs) per...,8.10,NUMBER
4,8,8.10.2,FB_BNK_ACCSS,Proportion of adults (15 years and older) with...,8.10,PERCENT
5,6,6.4.2,ER_H2O_STRESS,Level of water stress: freshwater withdrawal a...,6.4,PERCENT

## Global series catalogue

In [170]:
global_series_catalogue = pd.merge(pd.merge(indicator_list,tier_classification, how='left', on=['IndicatorCode']),
                                   global_series[['Indicator', 'Series', 'SeriesDesc', 'Units']], how = 'left', on = ['Indicator'])
global_series_catalogue.head(5)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode,Tier,Tier_Detailed,Notes,Series,SeriesDesc,Units
0,1,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,NaN,SI_POV_DAY1,Proportion of population below international p...,PERCENT
1,1,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,NaN,SI_POV_EMP1,Employed population below international povert...,PERCENT
2,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201,I,Tier I,NaN,SI_POV_NAHC,Proportion of population living below the nati...,PERCENT
3,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.2,"Proportion of men, women and children of all a...",C010202,II,Tier II,NaN,NaN,NaN,NaN
4,1,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,IAEG-SDG 3rd meeting: Lack of sufficient data ...,SI_COV_MATNL,[ILO] Proportion of mothers with newborns rece...,PERCENT

In [194]:
global_series_catalogue.shape

(504, 14)

Add a marker indicating that this is from the global sdg indicators database:

In [197]:
global_series_catalogue['side'] = 'Global'

In [198]:
global_series_catalogue.to_excel(global_indicator_dir + 'global_series_catalogue.xlsx',index=False, encoding='UTF-8')

# Consolidated SDG Matrix of Palestine

Read SDG data provided in multi-dimensional tables

In [180]:
indicator_list = pd.read_excel(output_dir + 'consolidated_mdt_REV4.xlsx')
indicator_list.head(5)

,INDICATOR,INDICATOR_CODE,INDICATOR_DESC_EN,SUBINDICATOR_CODE,SUBINDICATOR_DESC_AR,SUBINDICATOR_DESC_EN,AGE,EDUCATION_LEVEL,OCCUPATION,SEX,...,REF_AREA,TIME_PERIOD,OBS_COMMENT,OBS_STATUS,OBS_VALUE,UNIT_MEASURE,UNIT_MULT,BASE_PERIOD,TIME_DETAIL,SOURCE_DETAIL
0,1.2.1,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,NaN,NaN,NaN,BOTH,...,Gaza,2009,The data represent households and not populati...,NaN,38.3,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
1,1.2.1,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,NaN,NaN,NaN,BOTH,...,Gaza,2010,The data represent households and not populati...,NaN,38.0,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
2,1.2.1,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,NaN,NaN,NaN,BOTH,...,Gaza,2011,The data represent households and not populati...,NaN,38.8,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
3,1.2.1,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,NaN,NaN,NaN,BOTH,...,Gaza,2017,The data represent households and not populati...,NaN,53.0,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
4,1.2.1,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,NaN,NaN,NaN,BOTH,...,Palestine,2009,The data represent households and not populati...,NaN,26.2,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...

In [185]:
print(indicator_list.shape)
print(indicator_list.columns)

(3144, 21)
Index(['INDICATOR', 'INDICATOR_CODE', 'INDICATOR_DESC_EN', 'SUBINDICATOR_CODE',
       'SUBINDICATOR_DESC_AR', 'SUBINDICATOR_DESC_EN', 'AGE',
       'EDUCATION_LEVEL', 'OCCUPATION', 'SEX', 'URBANISATION', 'REF_AREA',
       'TIME_PERIOD', 'OBS_COMMENT', 'OBS_STATUS', 'OBS_VALUE', 'UNIT_MEASURE',
       'UNIT_MULT', 'BASE_PERIOD', 'TIME_DETAIL', 'SOURCE_DETAIL'],
      dtype='object')

In [199]:
pcbs_list = indicator_list[['INDICATOR_CODE', 'INDICATOR_DESC_EN', 'SUBINDICATOR_CODE','SUBINDICATOR_DESC_AR', 'SUBINDICATOR_DESC_EN', 'UNIT_MEASURE', 'UNIT_MULT', 'BASE_PERIOD', ]].drop_duplicates()
pcbs_list['side'] = 'pcbs'
pcbs_list.head(5)

,INDICATOR_CODE,INDICATOR_DESC_EN,SUBINDICATOR_CODE,SUBINDICATOR_DESC_AR,SUBINDICATOR_DESC_EN,UNIT_MEASURE,UNIT_MULT,BASE_PERIOD,side
0,C010201,Proportion of population living below the nati...,1.2.1_1,NaN,NaN,Percent,NaN,NaN,pcbs
20,C010501,"Number of deaths, missing persons, directly a...",1.5.1.1,عدد الوفيات بسبب\nالكوارث من كل 000 100 شخص,Number of deaths attributed to disasters per 1...,"Per 100,000",NaN,NaN,pcbs
26,C010501,"Number of deaths, missing persons, directly a...",1.5.1.2,عدد المفقودين بسبب\nالكوارث من كل 000 100 شخص,Number of missing persons attributed to disa...,"Per 100,000",NaN,NaN,pcbs
31,C010501,"Number of deaths, missing persons, directly a...",1.5.1.3,عدد المتضررين بسبب\nالكوارث من كل 000 100 شخص,Number of directly affected persons attributed...,"Per 100,000",NaN,NaN,pcbs
40,C010502,Direct economic loss attributed to disasters i...,1.5.2_1,NaN,NaN,USD,NaN,NaN,pcbs

In [200]:
print(pcbs_list.shape)
print(pcbs_list.columns)

(114, 9)
Index(['INDICATOR_CODE', 'INDICATOR_DESC_EN', 'SUBINDICATOR_CODE',
       'SUBINDICATOR_DESC_AR', 'SUBINDICATOR_DESC_EN', 'UNIT_MEASURE',
       'UNIT_MULT', 'BASE_PERIOD', 'side'],
      dtype='object')

In [201]:
pcbs_list.to_excel(output_dir + 'pcsb_series.xlsx',index=False, encoding='UTF-8')

Create a side-by side view:

In [218]:
x = pd.merge(global_series_catalogue, pcbs_list, how = 'outer', 
         left_on = ['IndicatorCode', 'side'],
         right_on = ['INDICATOR_CODE', 'side']
         )
x.head(5)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode,Tier,Tier_Detailed,...,Units,side,INDICATOR_CODE,INDICATOR_DESC_EN,SUBINDICATOR_CODE,SUBINDICATOR_DESC_AR,SUBINDICATOR_DESC_EN,UNIT_MEASURE,UNIT_MULT,BASE_PERIOD
0,1.0,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,...,PERCENT,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,...,PERCENT,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201,I,Tier I,...,PERCENT,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.2,"Proportion of men, women and children of all a...",C010202,II,Tier II,...,NaN,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,PERCENT,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [225]:
x['common_IndicatorCode'] = x['IndicatorCode']
x.common_IndicatorCode.fillna(x.INDICATOR_CODE, inplace=True)
x['common_IndicatorCode'].head(10)

0    C010101
1    C010101
2    C010201
3    C010202
4    C010301
5    C010301
6    C010301
7    C010301
8    C010301
9    C010301
Name: common_IndicatorCode, dtype: object

In [223]:
x.head(10)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode,Tier,Tier_Detailed,...,side,INDICATOR_CODE,INDICATOR_DESC_EN,SUBINDICATOR_CODE,SUBINDICATOR_DESC_AR,SUBINDICATOR_DESC_EN,UNIT_MEASURE,UNIT_MULT,BASE_PERIOD,common_IndicatorCode
0,1.0,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010101
1,1.0,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010101
2,1.0,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201,I,Tier I,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010201
3,1.0,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.2,"Proportion of men, women and children of all a...",C010202,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010202
4,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301
5,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301
6,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301
7,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301
8,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301
9,1.0,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,...,Global,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C010301

In [224]:
x.to_excel(output_dir + 'global_x_pcsb_series.xlsx',index=False, encoding='UTF-8')

# Data cleanup

At this stage, a manual proces of matching the data series available in PCSB with the data series available in the Global Indicator Database was carried out.  The main objective was to map `sub-indicators` definied in PCBS to `series` codes defined in the Global Indicator Database.

The resulting indicator catalogue is included in the excel file named `global_x_pcsb_series_edited2.xlsx`, and the consolidated data file is `consolidated_mdt_REV5.xlsx`

## Open the indicator catalogue

In [290]:
consolidated_indicator_list = pd.read_excel(output_dir + 'global_x_pcsb_series_edited2.xlsx')
consolidated_indicator_list.head(5)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode,Tier,Tier_Detailed,Notes,Series,SeriesDescEN,SeriesDescAR,Units,PCBS_Series,GlobalDatabase,Comment
0,1,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,NaN,SI_POV_DAY1,Proportion of population below international p...,NaN,PERCENT,0,NaN,NaN
1,1,End poverty in all its forms everywhere,NaN,1.1,"By 2030, eradicate extreme poverty for all peo...",1.1.1,Proportion of population below the internation...,C010101,I,Tier I,NaN,SI_POV_EMP1,Employed population below international povert...,NaN,PERCENT,0,NaN,NaN
2,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201,I,Tier I,NaN,SI_POV_NAHC,Proportion of population living below the nati...,NaN,PERCENT,1,Match,NaN
3,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.2,"Proportion of men, women and children of all a...",C010202,II,Tier II,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
4,1,End poverty in all its forms everywhere,NaN,1.3,Implement nationally appropriate social protec...,1.3.1,Proportion of population covered by social pro...,C010301,II,Tier II,IAEG-SDG 3rd meeting: Lack of sufficient data ...,SI_COV_MATNL,Proportion of mothers with newborns receiving ...,NaN,PERCENT,0,NaN,NaN

In [291]:
print(consolidated_indicator_list.shape)
print(consolidated_indicator_list.columns)

(533, 18)
Index(['Goal', 'GoalDesc', 'MOI_Group', 'Target', 'TargetDesc', 'Indicator',
       'IndicatorDesc', 'IndicatorCode', 'Tier', 'Tier_Detailed', 'Notes',
       'Series', 'SeriesDescEN', 'SeriesDescAR', 'Units', 'PCBS_Series',
       'GlobalDatabase', 'Comment'],
      dtype='object')

**Number of series in the global framework**

In [292]:
consolidated_indicator_list['Series'].loc[consolidated_indicator_list['GlobalDatabase'] != 'New'].drop_duplicates().count()

359

**Number of series in PCBS SDG matrix**

In [293]:
consolidated_indicator_list['Series'].loc[consolidated_indicator_list['PCBS_Series'] == 1].drop_duplicates().count()

101

**Number of series in PCBS SDG matrix that are also in the global framework**

In [294]:
consolidated_indicator_list['Series'].loc[(consolidated_indicator_list['PCBS_Series'] == 1) & (consolidated_indicator_list['GlobalDatabase'] != 'New')].drop_duplicates().count()

65

## Open the consolidated data matrix

In [295]:
consolidated_data_matrix = pd.read_excel(output_dir + 'consolidated_mdt_REV5.xlsx')
consolidated_data_matrix.head(5)

,INDICATOR_CODE,INDICATOR_DESC_EN,SERIES_CODE,SERIES_DESC_AR,SERIES_DESC_EN,AGE,EDUCATION_LEVEL,OCCUPATION,SEX,URBANISATION,INTERNET_SPEED,REF_AREA,TIME_PERIOD,FOOTNOTE,OBS_VALUE,UNIT_MEASURE,UNIT_MULT,BASE_PERIOD,TIME_DETAIL,SOURCE
0,C010201,Proportion of population living below the nati...,SI_POV_NAHC,NaN,NaN,NaN,NaN,NaN,BOTH,NaN,NaN,Gaza,2009,The data represent households and not populati...,38.3,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
1,C010201,Proportion of population living below the nati...,SI_POV_NAHC,NaN,NaN,NaN,NaN,NaN,BOTH,NaN,NaN,Gaza,2010,The data represent households and not populati...,38.0,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
2,C010201,Proportion of population living below the nati...,SI_POV_NAHC,NaN,NaN,NaN,NaN,NaN,BOTH,NaN,NaN,Gaza,2011,The data represent households and not populati...,38.8,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
3,C010201,Proportion of population living below the nati...,SI_POV_NAHC,NaN,NaN,NaN,NaN,NaN,BOTH,NaN,NaN,Gaza,2017,The data represent households and not populati...,53.0,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...
4,C010201,Proportion of population living below the nati...,SI_POV_NAHC,NaN,NaN,NaN,NaN,NaN,BOTH,NaN,NaN,Palestine,2009,The data represent households and not populati...,26.2,Percent,NaN,NaN,NaN,PCBS. Living Standards in the Palestinian Terr...

In [296]:
print(consolidated_data_matrix.shape)
print(consolidated_data_matrix.columns)

(3087, 20)
Index(['INDICATOR_CODE', 'INDICATOR_DESC_EN', 'SERIES_CODE', 'SERIES_DESC_AR',
       'SERIES_DESC_EN', 'AGE', 'EDUCATION_LEVEL', 'OCCUPATION', 'SEX',
       'URBANISATION', 'INTERNET_SPEED', 'REF_AREA', 'TIME_PERIOD', 'FOOTNOTE',
       'OBS_VALUE', 'UNIT_MEASURE', 'UNIT_MULT', 'BASE_PERIOD', 'TIME_DETAIL',
       'SOURCE'],
      dtype='object')

In [297]:
pcbs_list = consolidated_indicator_list.loc[consolidated_indicator_list['PCBS_Series'] == 1]
pcbs_list.head(4)

,Goal,GoalDesc,MOI_Group,Target,TargetDesc,Indicator,IndicatorDesc,IndicatorCode,Tier,Tier_Detailed,Notes,Series,SeriesDescEN,SeriesDescAR,Units,PCBS_Series,GlobalDatabase,Comment
2,1,End poverty in all its forms everywhere,NaN,1.2,"By 2030, reduce at least by half the proportio...",1.2.1,Proportion of population living below the nati...,C010201,I,Tier I,NaN,SI_POV_NAHC,Proportion of population living below the nati...,NaN,PERCENT,1,Match,NaN
21,1,End poverty in all its forms everywhere,NaN,1.5,"By 2030, build the resilience of the poor and ...",1.5.2,Direct economic loss attributed to disasters i...,C010502,II,Tier II,Sendai modification; Reviewed at 5th IAEG-SDG ...,VC_DSR_GDPLS,Direct economic loss attributed to disasters (...,NaN,CU_USD_M,1,Match,"check units and ""in relation to global GDP"""
38,2,"End hunger, achieve food security and improved...",NaN,2.1,"By 2030, end hunger and ensure access by all p...",2.1.2,Prevalence of moderate or severe food insecuri...,C020102,II,Tier II,Reviewed at Webex meeting in Nov. 2017 followi...,C020102_1,Prevalence of moderate food insecurity in the...,2.1.2 معدل انتشار انعدام الأمن الغذائي المتوسط...,Percent,1,New,subset of AG_PRD_FIESMSI
39,2,"End hunger, achieve food security and improved...",NaN,2.1,"By 2030, end hunger and ensure access by all p...",2.1.2,Prevalence of moderate or severe food insecuri...,C020102,II,Tier II,Reviewed at Webex meeting in Nov. 2017 followi...,C020102_2,Prevalence of severe food insecurity in the p...,2.1.2 معدل انتشار انعدام الأمن الغذائي الشديد ...,Percent,1,New,Subset of AG_PRD_FIESSI

In [298]:
print(pcbs_list.shape)
print(pcbs_list.columns)

(111, 18)
Index(['Goal', 'GoalDesc', 'MOI_Group', 'Target', 'TargetDesc', 'Indicator',
       'IndicatorDesc', 'IndicatorCode', 'Tier', 'Tier_Detailed', 'Notes',
       'Series', 'SeriesDescEN', 'SeriesDescAR', 'Units', 'PCBS_Series',
       'GlobalDatabase', 'Comment'],
      dtype='object')

In [299]:
for row in pcbs_list.itertuples(index=True, name='Pandas'):
    x = consolidated_indicator_list.loc[(consolidated_indicator_list['Indicator'] == getattr(row, 'Indicator') )& (consolidated_indicator_list['Series'] == getattr(row, 'Series') )]
    x = pd.merge(x, 
                 consolidated_data_matrix[['INDICATOR_CODE', 'SERIES_CODE', 'AGE', 'EDUCATION_LEVEL', 'OCCUPATION', 'SEX', 
                                           'URBANISATION', 'INTERNET_SPEED', 'REF_AREA', 'TIME_PERIOD', 'OBS_VALUE', 
                                           'UNIT_MEASURE', 'UNIT_MULT', 'BASE_PERIOD', 'FOOTNOTE', 'TIME_DETAIL', 'SOURCE']],
                 how = 'left',
                 left_on = ['IndicatorCode', 'Series'],
                 right_on = ['INDICATOR_CODE', 'SERIES_CODE']
              )
    # x.to_excel(output_dir + 'mdt_' +  getattr(row, 'Indicator') + '_' +  getattr(row, 'Series')+'.xlsx',index=False, encoding='UTF-8')
    
    x_columns = ['Goal', 'GoalDesc', 
                 'Target', 'TargetDesc', 
                 'Indicator', 'IndicatorDesc', 'IndicatorCode', 
                 'Series', 'SeriesDescEN', 'SeriesDescAR', 
                 'AGE', 'EDUCATION_LEVEL', 'OCCUPATION', 'SEX', 'URBANISATION', 'INTERNET_SPEED', 
                 'REF_AREA', 'TIME_PERIOD', 
                 'OBS_VALUE', 'UNIT_MEASURE', 'UNIT_MULT', 'BASE_PERIOD', 
                 'FOOTNOTE', 'TIME_DETAIL', 'SOURCE', 
                 'GlobalDatabase', 'Comment']

    
    ##############################################################################
    #
    # An example of converting a Pandas dataframe to an xlsx file
    # with column formats using Pandas and XlsxWriter.
    #
    # Copyright 2013-2019, John McNamara, jmcnamara@cpan.org
    #
    
    sheet = getattr(row, 'Indicator') + '_' +  getattr(row, 'Series')

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(output_dir + 'mdt_' +  sheet +'.xlsx', engine='xlsxwriter')

    # Convert the dataframe to an XlsxWriter Excel object.
    x[x_columns].to_excel(writer, sheet_name=sheet, index=False, encoding='UTF-8')

    # Get the xlsxwriter workbook and worksheet objects.
    workbook  = writer.book
    worksheet = writer.sheets[sheet]

    # Add some cell formats.
    #format1 = workbook.add_format({'num_format': '#,##0.00'})
    #format2 = workbook.add_format({'num_format': '0%'})
    #cell_format = workbook.add_format()
    #cell_format.set_text_wrap()

    # Set the column width and format.
    #worksheet.set_column('A:AI', 24, cell_format)
    worksheet.set_column('A:AI', 24, None)

    # Close the Pandas Excel writer and output the Excel file.
    writer.save()